title: Sahasra Javvadi - Student Portfolio
description: "I am from Class of 2026 learning to code and build cool projects."
owner_name: Sahasra Dheeksha Javvadi
author: Sahasra Javvadi
github_username: DJforest589
github_repo: "student" 
baseurl: "/student" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/Dheeksha589" }
#    - { platform: x, user_url: "https://x.com/Open_Coding" }
#    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md